const LOGIN = 'LOGIN';
const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
const LOGIN_FAIL = 'LOGIN_FAIL';

const SIGNUP = 'SIGNUP';
const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
const SIGNUP_FAIL = 'SIGNUP_FAIL';

const SET_USER_DATA = 'SET_USER_DATA';

export {
	LOGIN,
	LOGIN_SUCCESS,
	LOGIN_FAIL,
	SIGNUP,
	SIGNUP_SUCCESS,
	SIGNUP_FAIL,
	SET_USER_DATA,
};
